FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy
RUN apt update && apt install -y g++ curl cmake unzip libgomp1 && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger