#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;

namespace SIL.Machine.Morphology.HermitCrab.Conformance.SemanticCoverage;

/// <summary>
/// The checked-in denominator for rule-interaction coverage: one row per
/// <see cref="StratumInteractionPair"/> across every fixture, with the
/// <see cref="DomainRelation"/> <see cref="OrderingGenerator.CheckStratumPairDisjointDomains"/> resolved for
/// it. Unlike <see cref="CounterfactualLedger"/> or <see cref="EvidenceLedger"/>, this ledger is not evidence
/// of anything having been exercised -- it is purely the enumerated denominator, checked in so a change to
/// the enumeration or to a fixture's grammar is visible as a diff rather than only as a recomputed number.
/// </summary>
public static class RuleInteractionLedger
{
    public const string RelativePath = "conformance/rule-interaction-pairs.tsv";

    private const int ColumnCount = 9;

    public sealed record Row(
        string Fixture,
        string StratumA,
        string StratumB,
        StratumPairKind PairKind,
        StratumUnitKind UnitAKind,
        string UnitA,
        StratumUnitKind UnitBKind,
        string UnitB,
        DomainRelation Relation
    );

    /// <summary>Runs <see cref="OrderingGenerator.EnumerateStratumPairs"/> and classifies every pair
    /// for one fixture's grammar.</summary>
    public static IReadOnlyList<Row> Compute(XDocument grammar, string fixtureId)
    {
        ArgumentNullException.ThrowIfNull(grammar);
        ArgumentNullException.ThrowIfNull(fixtureId);

        return OrderingGenerator
            .EnumerateStratumPairs(grammar, fixtureId)
            .Select(pair => new Row(
                pair.FixtureId,
                pair.StratumALabel,
                pair.StratumBLabel,
                pair.Kind,
                pair.UnitA.Kind,
                pair.UnitA.Label,
                pair.UnitB.Kind,
                pair.UnitB.Label,
                OrderingGenerator.CheckStratumPairDisjointDomains(grammar, pair).Relation
            ))
            .ToArray();
    }

    public static void Write(string repositoryRoot, IReadOnlyList<Row> rows)
    {
        ArgumentNullException.ThrowIfNull(repositoryRoot);
        ArgumentNullException.ThrowIfNull(rows);
        string path = Path.Combine(repositoryRoot, RelativePath.Replace('/', Path.DirectorySeparatorChar));
        File.WriteAllText(path, ToText(rows));
    }

    /// <summary>
    /// Renders the ledger deterministically (fixture, then Stratum ordinals, then unit labels) so two runs
    /// over an unchanged corpus byte-for-byte agree -- <c>RuleInteractionPairsCheckedInLedgerIsUpToDate</c>
    /// depends on this for its drift check.
    /// </summary>
    public static string ToText(IReadOnlyList<Row> rows)
    {
        ArgumentNullException.ThrowIfNull(rows);
        var writer = new StringWriter();
        writer.WriteLine(
            "# GENERATED by hc-conformance --write-rule-interaction-pairs. One line per pipeline-permitted"
        );
        writer.WriteLine(
            "# ordered pair of rule-bearing units within a Stratum (or between two adjacent Strata) --"
        );
        writer.WriteLine(
            "# OrderingGenerator.EnumerateStratumPairs's denominator for rule-interaction coverage, classified"
        );
        writer.WriteLine(
            "# by CheckStratumPairDisjointDomains. Self-pairs are included (see the method doc for why); an"
        );
        writer.WriteLine(
            "# AffixTemplate is one unit, never exploded into its Slot rules -- those are already pinned by"
        );
        writer.WriteLine(
            "# OrderingGenerator's adjacent-pair AffixTemplateSlots list. pair_kind is same-stage, cross-stage,"
        );
        writer.WriteLine(
            "# or cross-stratum. domain_relation is only ever Disjoint/Overlaps for a PhonologicalRule pair;"
        );
        writer.WriteLine("# every other unit-kind combination is Undetermined by construction.");
        writer.WriteLine(
            "fixture\tstratum_a\tstratum_b\tpair_kind\tunit_a_kind\tunit_a\tunit_b_kind\tunit_b\tdomain_relation"
        );
        foreach (
            Row row in rows
                .OrderBy(r => r.Fixture, StringComparer.Ordinal)
                .ThenBy(r => r.StratumA, StringComparer.Ordinal)
                .ThenBy(r => r.PairKind)
                .ThenBy(r => r.UnitAKind)
                .ThenBy(r => r.UnitA, StringComparer.Ordinal)
                .ThenBy(r => r.UnitBKind)
                .ThenBy(r => r.UnitB, StringComparer.Ordinal)
        )
        {
            writer.WriteLine(
                string.Join(
                    '\t',
                    row.Fixture,
                    row.StratumA,
                    row.StratumB,
                    row.PairKind,
                    row.UnitAKind,
                    row.UnitA,
                    row.UnitBKind,
                    row.UnitB,
                    row.Relation
                )
            );
        }
        return writer.ToString();
    }

    /// <summary>Reads the checked-in ledger, or an empty list if it has never been written.</summary>
    public static IReadOnlyList<Row> Read(string repositoryRoot)
    {
        ArgumentNullException.ThrowIfNull(repositoryRoot);
        string path = Path.Combine(repositoryRoot, RelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
            return Array.Empty<Row>();

        var rows = new List<Row>();
        foreach (string raw in File.ReadAllLines(path))
        {
            string line = raw.Trim();
            if (
                line.Length == 0
                || line.StartsWith("#", StringComparison.Ordinal)
                || line.StartsWith("fixture\t", StringComparison.Ordinal)
            )
            {
                continue;
            }

            string[] fields = line.Split('\t');
            if (fields.Length != ColumnCount)
                throw new FormatException($"{RelativePath}: '{line}' must be {ColumnCount} tab-separated fields");
            if (!Enum.TryParse(fields[3], out StratumPairKind pairKind))
                throw new FormatException($"{RelativePath}: unknown pair kind '{fields[3]}'");
            if (!Enum.TryParse(fields[4], out StratumUnitKind unitAKind))
                throw new FormatException($"{RelativePath}: unknown unit kind '{fields[4]}'");
            if (!Enum.TryParse(fields[6], out StratumUnitKind unitBKind))
                throw new FormatException($"{RelativePath}: unknown unit kind '{fields[6]}'");
            if (!Enum.TryParse(fields[8], out DomainRelation relation))
                throw new FormatException($"{RelativePath}: unknown domain relation '{fields[8]}'");

            rows.Add(
                new Row(fields[0], fields[1], fields[2], pairKind, unitAKind, fields[5], unitBKind, fields[7], relation)
            );
        }

        return rows;
    }
}
